### ISSUE TITLE
Binary CI in R

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#7]
The reason for the difference still needs to be looked into
```{r}
n <- 1
r <- 1
 
library(Hmisc)
binconf(r,n,method="exact",alpha=0.05)
 
library(RBesT)
BinaryExactCI(r,n,alpha=0.05)
 
```

**Comment by jsrivj** [comment]
@statasaurus 
Hi I am getting below issue when I do Renv restore , 
![image](https://user-images.githubusercontent.com/114507280/232545021-b232bed8-d276-47c4-a960-065e91083fb7.png)
Kindly let me know your thoughts.

**Comment by statasaurus** [comment]
Can you try to reinstall renv then try again?

**Comment by muridaehsr** [comment]
I took a deep dive into this issue. Below, I extracted the relevant sections of Hmisc::binconf and RBesT::BinaryExactCI to try and figure out how each of them worked. They take different approaches to end up in very similar, often identical, results.

After some trial and error, I have found that results were identical except in the following limited cases:
x = 0, in which case the lower limit does not match.
x = n, in which case the upper limit does not match.

In the Hmisc code, the derivation of pp requires x<n otherwise it imputes to 1.

Taking a look at the wikipedia page for binomial proportion confidence interval, the derivation used by Hmisc appears to closely resemble the Jeffreys Interval which states the following:
"In order to avoid the coverage probability tending to zero when p→0 or 1 , when x =0 the upper limit is calculated as before but the lower limit is set to 0 , and when x = n the lower limit is calculated as before but the upper limit is set to 1 ."

Essentially, the method used by Hmisc defaults the lower limit to 0 when x=0, and the upper limit defaults to 1 when x=n.

The BinaryExactCI code appears most similar to the Clopper-Pearson interval, presented in the manner that is dependent on quantiles from the beta distribution. The wiki page describes their handling of the special cases of x=0 and x=n as follows:

***
<img width="797" alt="image" src="https://github.com/user-attachments/assets/98a214bc-52ca-4e42-b447-a8f67b337606">

***

Looking at the RBesT::BinaryExactCI derivation again, we see that indeed the derivation is based on the quantiles from the beta distribution, including the special handling of the cases where x=0 and x=n.

Following this investigation, I think the reason for the discrepancy is due to the difference between the Jefrreys Interval and the Clopper-Pearson Interval for handling these two very specific scenarios. I am also way out of my depth on this, so please double check my work to make sure my interpretation is correct.

***

# Hmisc::binconf

x = 1
n = 1

nu1 <- 2 * (n - x + 1)
nu2 <- 2 * x

if (x > 0) x/(x + qf(1 - alpha/2, nu1, nu2) * (n - x + 1)) else 0 # Lower

nu1p <- nu2 + 2
nu2p <- nu1 - 2
pp <- if (x < n) qf(1 - alpha/2, nu1p, nu2p) else 1

((x + 1) * pp)/(n - x + (x + 1) * pp) # Upper

***

# RBesT::BinaryExactCI

r = 1
n = 1

alpha2 <- alpha/2
Low <- alpha2
High <- 1 - alpha2
pLow <- qbeta(Low, r + (r == 0), n - r + 1)
pHigh <- qbeta(High, r + 1, n - r + ((n - r) == 0))
nms <- c(paste(round(100 * Low, 1), "%", sep = ""), paste(round(100 * High, 1), "%", sep = ""))
CI <- cbind(pLow, pHigh)
colnames(CI) <- nms
if (drop) CI <- drop(CI)

CI

***

Once we confirm this, should we include a note that there are different acceptable methods for deriving an exact binomial proportion confidence interval, and point readers to these 2 examples and the wiki page for awareness of possible discrepancies in cases where x=0 (lower limit) and x=n (upper limit)?

**Comment by muridaehsr** [comment]
Correction to my above comment, I re-read the code for Hmisc::binconf and its documentation, and they actually say the following: The "exact" method uses the F distribution to compute exact (based on the binomial cdf) intervals. This appears to be just another derivation of the Clopper and Pearson approach.

Documentation for RBesT::BinaryExactCI confirms that the Clopper and Pearson using quantiles of the beta distribution was used to derive exact confidence intervals.

Looking more closely at the RBest derivation specifically, the qbeta derivations for pLow and pHigh may actually be incorrect according to the wiki page, which states:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/315e67f0-f120-464b-940b-4570344a1423">

As we can see, the intervals don't match. When I make a slight change to pHigh for example, we end up having an upper confidence interval that matches the Hmisc derivation when x=0 (lower limit) and when x=n (upper limit).

Before:
pLow <- qbeta(Low, r + (r == 0), n - r + 1)
pHigh <- qbeta(High, r + 1, n - r + ((n - r) == 0))

After:
pLow <- qbeta(Low, r, n - r + 1)
pHigh <- qbeta(High, r + 1, n - r)

I wonder what the rationale was for the RBesT script to add in the logical conditionals for (r==0) and ((n-r)==0)... is this a widely accepted correction?

**Comment by DrLynTaylor** [comment]
Thank you so much @muridaehsr, this is brilliant.  I will use the above to update the pages I wrote on CIs for proportions so that this is clearly identified.  Even if we don't know why it was done, at least we now know what causes the difference.

**Comment by DrLynTaylor** [comment]
Hi @muridaehsr .   I have now updated the page here with the information above: https://psiaims.github.io/CAMIS/R/ci_for_prop.html    Would you mind having a read through and confirming that i've captured everything correctly.   Once confirmed i'll close down this issue & Thanks again for investigating for us.
